### ISSUE TITLE
Essay 4 Currently .DOCX Format

### ISSUE THREAD

**Issue by DABiastate** [thiennp94/SE339_Essay4#1]
## Essay 4 Description
* Document should be in Markdown format (Essay4.md)
* Document should be added to via pull requests
* *and more*

Please see the below link for markdown styling:
[*Basic writing and formatting syntax*](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

If you don't PR, please provide a writeup of how the work was divided. Other than that, content currently looks on the right path.

Sincerely,

TA

**Comment by DABiastate** [comment]
@me in Discord when there is a draft version you want feedback on.

**Comment by thiennp94** [comment]
I have converted Essay 4 to MarkDown format. Our group worked together to update the content of this document. So, the task is divided equally among team members:
Elvis: Introduction and edit
Jack: Conclusion and edit
Jacob: Body and edit
Phuoc: Body and edit
